os: linux
language: generic

script:
  - node ".stdlib-test/collections/base.js"
  - node ".stdlib-test/collections/predicate.js"
  - node ".stdlib-test/collections/transform.js"
  - node ".stdlib-test/geometry.js"
  - node ".stdlib-test/math.js"
  - node ".stdlib-test/standard.js"
  - node ".stdlib-test/text.js"
  - node ".stdlib-test/time.js"
